services:
  eventrentlast-backend:
    image: eventrentlast-backend:latest
    restart: unless-stopped
    environment:
      PORT: "4320"
    volumes:
      - /datastore/eventrentlast/uploads:/app/uploads
      - /datastore/eventrentlast/data:/app/data
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.eventrentlast-api.rule=Host(`eventrentlast.octotech.az`) && (PathPrefix(`/api`) || PathPrefix(`/uploads`))'
      - 'traefik.http.routers.eventrentlast-api.entrypoints=web'
      - 'traefik.http.routers.eventrentlast-api.priority=100'
      - 'traefik.http.services.eventrentlast-api.loadbalancer.server.port=4320'

  eventrentlast-frontend:
    image: eventrentlast-frontend:latest
    restart: unless-stopped
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.eventrentlast.rule=Host(`eventrentlast.octotech.az`)'
      - 'traefik.http.routers.eventrentlast.entrypoints=web'
      - 'traefik.http.services.eventrentlast.loadbalancer.server.port=80'

networks:
  edge:
    external: true
