services:
  eventrentlast-backend:
    image: ghcr.io/aliyabuz25/eventrentlast-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    environment:
      PORT: "4320"
      APP_URL: "https://erent.octotech.az"
      JWT_SECRET: "951b81298102b972ff28e19bfd9df544d11fd8d5f34123fb247b2b9409eea624"
    volumes:
      - /datastore/eventrentlast/uploads:/app/uploads
      - /datastore/eventrentlast/data:/app/data
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.eventrentlast-api.rule=Host(`erent.octotech.az`) && (PathPrefix(`/api`) || PathPrefix(`/uploads`))'
      - 'traefik.http.routers.eventrentlast-api.entrypoints=web'
      - 'traefik.http.routers.eventrentlast-api.priority=100'
      - 'traefik.http.services.eventrentlast-api.loadbalancer.server.port=4320'

  eventrentlast-frontend:
    image: ghcr.io/aliyabuz25/eventrentlast-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.eventrentlast.rule=Host(`erent.octotech.az`)'
      - 'traefik.http.routers.eventrentlast.entrypoints=web'
      - 'traefik.http.services.eventrentlast.loadbalancer.server.port=80'

networks:
  edge:
    external: true
